[workspace]
resolver = "2"
members = [
  "crates/*",
]
default-members = ["crates/mangacross-rss-cli"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.17.0", default-features = false }
tracing = "0.1.40"
